// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEyTjadDrLsweFSKPNEHpCdWvxUUAcapk',
    appId: '1:771064123174:web:ecc0f6e1f32c653a82fbe7',
    messagingSenderId: '771064123174',
    projectId: 'send-message-3f15d',
    authDomain: 'send-message-3f15d.firebaseapp.com',
    storageBucket: 'send-message-3f15d.appspot.com',
    measurementId: 'G-51YX15LYME',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD3ruNauY33YxbQMflO9q9ST_sLJc694c',
    appId: '1:771064123174:android:d6d162bd31fe685182fbe7',
    messagingSenderId: '771064123174',
    projectId: 'send-message-3f15d',
    storageBucket: 'send-message-3f15d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJBOXFdsUVWwmZAN-88hUonqWCr5wAzt4',
    appId: '1:771064123174:ios:e4e20108b87b7fcf82fbe7',
    messagingSenderId: '771064123174',
    projectId: 'send-message-3f15d',
    storageBucket: 'send-message-3f15d.appspot.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJBOXFdsUVWwmZAN-88hUonqWCr5wAzt4',
    appId: '1:771064123174:ios:e4e20108b87b7fcf82fbe7',
    messagingSenderId: '771064123174',
    projectId: 'send-message-3f15d',
    storageBucket: 'send-message-3f15d.appspot.com',
    iosBundleId: 'com.example.myProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEyTjadDrLsweFSKPNEHpCdWvxUUAcapk',
    appId: '1:771064123174:web:d2188fb62ad1e82f82fbe7',
    messagingSenderId: '771064123174',
    projectId: 'send-message-3f15d',
    authDomain: 'send-message-3f15d.firebaseapp.com',
    storageBucket: 'send-message-3f15d.appspot.com',
    measurementId: 'G-G2L05YV46J',
  );

}